framework:
  - terraform

external-checks-dir:
  - ./custom_checks

soft-fail: false

quiet: false

skip-check:
  - CKV_AWS_135
  - CKV_AWS_126
  - CKV_AWS_260
  - CKV_AWS_145
  - CKV2_AWS_11
  - CKV2_AWS_5
  - CKV_AWS_18 
  - CKV_AWS_144
  - CKV2_AWS_28
  - CKV2_AWS_62
  - CKV2_AWS_71