name: Unit tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  filter-updated-directories:
    runs-on: ubuntu-24.04
    outputs:
        app_changed: ${{ steps.filter_files.outputs.app }}
    steps:
        - name: Checkout code
          uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 

        - name: Filter changed files
          id: filter_files
          uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
          with:
                filters: |
                  app:
                    - 'app/**'

  run-tests:
    runs-on: ubuntu-24.04
    needs: filter-updated-directories
    if: ${{ needs.filter-updated-directories.outputs.app_changed == 'true' }}
    steps:
        - name: Checkout code
          uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

        - name: Setup node environment
          uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f
          with:
              node-version-file: app/package.json
              cache: npm
              cache-dependency-path: app/package-lock.json

        - name: Install app dependencies
          working-directory: app
          run: npm ci

        - name: Run tests
          working-directory: app
          run: npm test